/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProsRouteImport } from './routes/pros'
import { Route as SmsOptInRouteImport } from './routes/sms-opt-in'
import { Route as TermsRouteImport } from './routes/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProsRoute = ProsRouteImport.update({
  id: '/pros',
  path: '/pros',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsOptInRoute = SmsOptInRouteImport.update({
  id: '/sms-opt-in',
  path: '/sms-opt-in',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/pros': typeof ProsRoute
  '/sms-opt-in': typeof SmsOptInRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/pros': typeof ProsRoute
  '/sms-opt-in': typeof SmsOptInRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/pros': typeof ProsRoute
  '/sms-opt-in': typeof SmsOptInRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/faq' | '/privacy' | '/pros' | '/sms-opt-in' | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/faq' | '/privacy' | '/pros' | '/sms-opt-in' | '/terms'
  id:
    '__root__' | '/' | '/faq' | '/privacy' | '/pros' | '/sms-opt-in' | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  ProsRoute: typeof ProsRoute
  SmsOptInRoute: typeof SmsOptInRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pros': {
      id: '/pros'
      path: '/pros'
      fullPath: '/pros'
      preLoaderRoute: typeof ProsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms-opt-in': {
      id: '/sms-opt-in'
      path: '/sms-opt-in'
      fullPath: '/sms-opt-in'
      preLoaderRoute: typeof SmsOptInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  ProsRoute: ProsRoute,
  SmsOptInRoute: SmsOptInRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
